### ISSUE TITLE
coredump

### ISSUE THREAD

**Issue by fanbinbill** [MarcJHuber/event-driven-servers#135]
您好，我是用昨天的最新版本，发现存在偶发 coredump 情况

Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `tac_plus: 11 connections                            '.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

-------

(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fec1010e535 in __GI_abort () at abort.c:79
#2  0x00007fec10165518 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fec1026f28d "%s\n")
    at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fec1016bc3a in malloc_printerr (str=str@entry=0x7fec10270c18 "mremap_chunk(): invalid pointer") at malloc.c:5359
#4  0x00007fec1016c2fc in mremap_chunk (p=p@entry=0x55c637994260, new_size=new_size@entry=98320) at malloc.c:2861
#5  0x00007fec10170d43 in __GI___libc_realloc (oldmem=0x55c637994270, bytes=98304) at malloc.c:3204
#6  0x00007fec10674da1 in XXrealloc () from /usr/local/lib64/libmavis.so
#7  0x00007fec106787b3 in epoll_io_register () from /usr/local/lib64/libmavis.so
#8  0x00007fec10676238 in io_register () from /usr/local/lib64/libmavis.so
#9  0x000055c637200dfe in accept_control_common ()
#10 0x000055c6371ffbb0 in accept_control_raw ()
#11 0x000055c6372010dd in accept_control ()
#12 0x00007fec10676041 in io_poll () from /usr/local/lib64/libmavis.so
#13 0x00007fec10679e20 in io_main () from /usr/local/lib64/libmavis.so

**Comment by fanbinbill** [comment]
# ss -s
Total: 383841
TCP:   384295 (estab 137, closed 199773, orphaned 0, timewait 852)

Transport Total     IP        IPv6
RAW	  1         1         0
UDP	  81        12        69
TCP	  184522    184462    60
INET	  184604    184475    129

同时系统看到存在大量等待 closed 状态连接

**Comment by MarcJHuber** [comment]
Hi,

thanks for reporting, I think f764969ac9fc195c82098e8696d7cdc2ce2327eb fixes this.

Cheers,

Marc

**Comment by MarcJHuber** [comment]
Hi,

the core issue is fixed in caa386f94df1bd2f2dd9b56d4f6c2111dcac4f9e -- I didn't expect MSG_PEEK to actually add a SCM_RIGHTS file descriptor.

Thanks,

Marc
